services:
  ansible-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
      args:
        SERVER_USER_NAME: ${SERVER_USER_NAME}
        SERVER_USER_PASSWORD: ${SERVER_USER_PASSWORD}
    hostname: ansible-server
    container_name: ansible-server
    networks:
      - ansible-net
    ports:
    - "2222:22"
    volumes:
      - ./ansible:/home/${SERVER_USER_NAME}/ansible
      - ./ansible_config:/etc/ansible  # New volume for ansible.cfg
    tty: true

  client1:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
      args:
        CLIENT_USER_NAME: ${CLIENT_USER_NAME}
    hostname: ansible-client1
    container_name: ansible-client1
    networks:
      - ansible-net

  client2:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
      args:
        CLIENT_USER_NAME: ${CLIENT_USER_NAME}
    hostname: ansible-client2
    container_name: ansible-client2
    networks:
      - ansible-net

networks:
  ansible-net:
    driver: bridge
